# Generated by Django 2.0.13 on 2019-03-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_passworld', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LedNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_text', models.CharField(max_length=100)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.Custom')),
            ],
        ),
    ]
