# Generated by Django 2.0.13 on 2019-03-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0002_lednumber_address_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='user_passworld',
            new_name='user_password',
        ),
    ]
