# Generated by Django 2.0.13 on 2019-04-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0003_auto_20190318_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=500)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.Custom')),
            ],
        ),
    ]
