# Generated by Django 2.0.13 on 2019-05-17 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0004_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=500)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.Custom')),
            ],
        ),
    ]
